"""add geocoding columns to plumber_prospects

Revision ID: 9509d48f1d90
Revises: 
Create Date: 2026-02-28 19:23:41.262424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9509d48f1d90'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plumber_prospects', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('plumber_prospects', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('plumber_prospects', sa.Column('geocoded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plumber_prospects', 'geocoded_at')
    op.drop_column('plumber_prospects', 'longitude')
    op.drop_column('plumber_prospects', 'latitude')
    # ### end Alembic commands ###
